#!/bin/bash
set -euxo pipefail

# We always want the latest image
docker pull ubuntu:20.04

# CACHEBUST means this will apply the updates once a day
docker build . -t distributions \
    --build-arg CACHEBUST=`date --iso-8601=date` \
    --build-arg USER_UID=$(id -u "$USER") \
    --build-arg GO_IPFS_VER=${GO_IPFS_VER:-$(curl -s https://dist.ipfs.tech/go-ipfs/versions | tail -n 1)} # match http api client version on CI

# We use host networking as the build process assumes a fairly long-lived ipfs
# node has the CIDs (we give them to the collab cluster to pin) 
docker run --rm -i --network host -e DIST_ROOT -v `pwd`:/build distributions "$@"
