name: Nightly

on:
  ## Allow manual invocation
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # UTC

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: sudo snap install ipfs jq
      - run: ipfs init --profile server
      - run: ipfs daemon &
      - name: Wait for ipfs daemon
        run: npx wait-port http://127.0.0.1:8080/api/v0/version
      - name: Connect to ipfs cluster
        run: ipfs swarm connect /dnsaddr/cluster.ipfs.io
      - run: make deps nightly all_dists
      - run: make publish
